import { existsSync } from "node:fs";
import { writeFile } from "node:fs/promises";
import { randomBytes } from "node:crypto";
import path from "node:path";

const destination = path.join(process.cwd(), ".env.local");

if (existsSync(destination)) {
  console.log(".env.local already exists. Leaving it unchanged.");
  process.exit(0);
}

const encryptionKey = randomBytes(32).toString("base64");

const contents = `# Generated by pnpm local:setup
LOCAL_MODE=true
NEXT_PUBLIC_APP_URL=http://localhost:3000
ENCRYPTION_KEY_BASE64=${encryptionKey}

DATABASE_URL=postgresql://continuity:continuity@127.0.0.1:5432/continuity?schema=public

S3_ENDPOINT=http://127.0.0.1:9000
S3_REGION=us-east-1
S3_FORCE_PATH_STYLE=true
S3_ACCESS_KEY_ID=continuity
S3_SECRET_ACCESS_KEY=continuity-local-secret
S3_BUCKET=continuity

INNGEST_DEV=http://127.0.0.1:8288

# Optional: only needed for AI-assisted script breakdown.
GEMINI_API_KEY=
`;

await writeFile(destination, contents, { encoding: "utf8", mode: 0o600 });

console.log("Created .env.local for free local mode.");
console.log("No Clerk or Cloudflare credentials are required in this mode.");
