import { existsSync } from "node:fs";
import { readFile, writeFile } from "node:fs/promises";
import { randomBytes } from "node:crypto";
import os from "node:os";
import path from "node:path";

const root = process.cwd();
const webEnvPath = path.join(root, "apps", "web", ".env.local");
const dbEnvPath = path.join(root, "packages", "db", ".env");
const databaseUrl =
  "postgresql://continuity:continuity@127.0.0.1:5432/continuity?schema=public";

function privateIpv4(address) {
  return (
    address.startsWith("10.") ||
    address.startsWith("192.168.") ||
    /^172\.(1[6-9]|2\d|3[01])\./.test(address)
  );
}

function lanAddress() {
  const candidates = [];

  for (const entries of Object.values(os.networkInterfaces())) {
    for (const entry of entries ?? []) {
      if (
        entry.family === "IPv4" &&
        !entry.internal &&
        privateIpv4(entry.address)
      ) {
        candidates.push(entry.address);
      }
    }
  }

  return candidates[0] || "127.0.0.1";
}

const host = lanAddress();
const appUrl = `http://${host}:3000`;
const storageEndpoint = `http://${host}:9000`;
const encryptionKey = randomBytes(32).toString("base64");

const webContents = `# Generated by pnpm local:setup
LOCAL_MODE=true
NEXT_PUBLIC_APP_URL=${appUrl}
LOCAL_LAN_HOST=${host}
ENCRYPTION_KEY_BASE64=${encryptionKey}

DATABASE_URL=${databaseUrl}

S3_ENDPOINT=${storageEndpoint}
S3_REGION=us-east-1
S3_FORCE_PATH_STYLE=true
S3_ACCESS_KEY_ID=continuity
S3_SECRET_ACCESS_KEY=continuity-local-secret
S3_BUCKET=continuity

INNGEST_DEV=http://127.0.0.1:8288

# Optional. Local mode uses the free heuristic scene splitter when this is blank.
GEMINI_API_KEY=
`;

const dbContents = `# Generated by pnpm local:setup
DATABASE_URL=${databaseUrl}
`;

function replaceLine(contents, name, value) {
  const line = `${name}=${value}`;
  const expression = new RegExp(`^${name}=.*$`, "m");
  return expression.test(contents)
    ? contents.replace(expression, line)
    : contents.trimEnd() + "\n" + line + "\n";
}

if (existsSync(webEnvPath)) {
  let existing = await readFile(webEnvPath, "utf8");
  existing = replaceLine(existing, "LOCAL_MODE", "true");
  existing = replaceLine(existing, "NEXT_PUBLIC_APP_URL", appUrl);
  existing = replaceLine(existing, "LOCAL_LAN_HOST", host);
  existing = replaceLine(existing, "S3_ENDPOINT", storageEndpoint);
  await writeFile(webEnvPath, existing, { encoding: "utf8", mode: 0o600 });
  console.log(`Updated local LAN endpoints in apps/web/.env.local (${host}).`);
} else {
  await writeFile(webEnvPath, webContents, {
    encoding: "utf8",
    mode: 0o600,
  });
  console.log("Created apps/web/.env.local for free local mode.");
}

if (existsSync(dbEnvPath)) {
  console.log("packages/db/.env already exists. Leaving it unchanged.");
} else {
  await writeFile(dbEnvPath, dbContents, {
    encoding: "utf8",
    mode: 0o600,
  });
  console.log("Created packages/db/.env for local Prisma.");
}

console.log(`PC app:    http://localhost:3000`);
console.log(`Phone URL: ${appUrl}`);
console.log("No Clerk or Cloudflare credentials are required in local mode.");
