import { existsSync } from "node:fs";
import { writeFile } from "node:fs/promises";
import { randomBytes } from "node:crypto";
import path from "node:path";

const root = process.cwd();
const webEnvPath = path.join(root, "apps", "web", ".env.local");
const dbEnvPath = path.join(root, "packages", "db", ".env");
const databaseUrl =
  "postgresql://continuity:continuity@127.0.0.1:5432/continuity?schema=public";

const encryptionKey = randomBytes(32).toString("base64");

const webContents = `# Generated by pnpm local:setup
LOCAL_MODE=true
NEXT_PUBLIC_APP_URL=http://localhost:3000
ENCRYPTION_KEY_BASE64=${encryptionKey}

DATABASE_URL=${databaseUrl}

S3_ENDPOINT=http://127.0.0.1:9000
S3_REGION=us-east-1
S3_FORCE_PATH_STYLE=true
S3_ACCESS_KEY_ID=continuity
S3_SECRET_ACCESS_KEY=continuity-local-secret
S3_BUCKET=continuity

INNGEST_DEV=http://127.0.0.1:8288

# Optional. Local mode uses the free heuristic scene splitter when this is blank.
GEMINI_API_KEY=
`;

const dbContents = `# Generated by pnpm local:setup
DATABASE_URL=${databaseUrl}
`;

let created = 0;

if (existsSync(webEnvPath)) {
  console.log("apps/web/.env.local already exists. Leaving it unchanged.");
} else {
  await writeFile(webEnvPath, webContents, {
    encoding: "utf8",
    mode: 0o600,
  });
  console.log("Created apps/web/.env.local for free local mode.");
  created += 1;
}

if (existsSync(dbEnvPath)) {
  console.log("packages/db/.env already exists. Leaving it unchanged.");
} else {
  await writeFile(dbEnvPath, dbContents, {
    encoding: "utf8",
    mode: 0o600,
  });
  console.log("Created packages/db/.env for local Prisma.");
  created += 1;
}

if (created > 0) {
  console.log("No Clerk or Cloudflare credentials are required in local mode.");
}
